// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ClickSubmitController from "./click_submit_controller.js"
application.register("click-submit", ClickSubmitController)

import CoffeePhotoUploaderController from "./coffee_photo_uploader_controller.js"
application.register("coffee-photo-uploader", CoffeePhotoUploaderController)

import CoffeeSearchFormController from "./coffee_search_form_controller.js"
application.register("coffee-search-form", CoffeeSearchFormController)

import ConfirmationController from "./confirmation_controller.js"
application.register("confirmation", ConfirmationController)

import LogEntryFormController from "./log_entry_form_controller.js"
application.register("log-entry-form", LogEntryFormController)

import SortCoffeesController from "./sort_coffees_controller"
application.register("sort-coffees", SortCoffeesController)

import VisitController from "./visit_controller.js"
application.register("visit", VisitController)
