version: "3.9"
services:
  app:
    build:
      context: .
      target: prod
      args:
        RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://coffee_log:password@db/coffee_log
      - TEST_DATABASE_URL=postgres://coffee_log:password@db/coffee_log_test
      - RAILS_ENV=production
      - AWS_REGION
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - RAILS_MASTER_KEY
    ports:
      - "3000:8080"
    volumes:
      - tmp:/usr/src/app/tmp
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: coffee_log
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  tmp:
  postgres:
