# fly.toml app configuration file generated for coffee-log on 2023-06-04T20:13:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coffee-log"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/up"

[env]
  RAILS_ENV = "fly"
