# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EmailVerificationMailer`.
# Please instead update this file by running `bin/tapioca dsl EmailVerificationMailer`.

class EmailVerificationMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def verification_link; end
  end
end
