# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PasswordResetRequestMailer`.
# Please instead update this file by running `bin/tapioca dsl PasswordResetRequestMailer`.

class PasswordResetRequestMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def reset_password_link; end
  end
end
