# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PasswordResetRequest`.
# Please instead update this file by running `bin/tapioca dsl PasswordResetRequest`.

class PasswordResetRequest
  sig { returns(T.nilable(::String)) }
  def email; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def email=(value); end
end
