# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SignupFormMailer`.
# Please instead update this file by running `bin/tapioca dsl SignupFormMailer`.

class SignupFormMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def welcome_email; end
  end
end
