name: Fly Deploy
on:
  workflow_call:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  prod:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - run: echo FLY_API_TOKEN=$FLY_API_TOKEN
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
