name: Fly Deploy
on:
  workflow_call:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  prod:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -e RAILS_MASTER_KEY="$RAILS_MASTER_KEY"
