name: Rails - Install dependencies and run unit tests

on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: [ '5432:5432' ]
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev

#      - uses: nanasess/setup-chromedriver@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: setup yarn and build assets
        run: |
          yarn install
          yarn run build

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

#      - name: Run linters
#        run: |
#          bin/rubocop

      - name: Run unit tests
        env:
          DISPLAY: :99
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        run: |
          bin/rails db:setup
          bin/rails test
#          bin/rails test:system
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
